repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-ast
      - id: check-docstring-first
      - id: check-yaml

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except
          - flake8-bandit
          - flake8-comprehensions
          - flake8-mutable
          - flake8-bugbear
          - flake8-per-file-ignores

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --settings-path
          - pyproject.toml
          - --profile
          - black
          - --filter-files
          - --magic-placement
          - --py
          - auto
          - bot

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
        args:
          - --preview

  - repo: https://github.com/pdm-project/pdm
    rev: 2.12.2
    hooks:
      - id: pdm-export
        args: [ '-o', 'requirements.txt', '--without-hashes' ]
        files: ^pdm.lock$
