services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "adminpass"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    expose:
      - 5432

  web:
    build:
      context: .
      dockerfile: deploy/web/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/src
    ports:
      - "8088:80"
    depends_on:
      db:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_started
